#!/bin/bash

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

# Globals
OMV_CONFIG_XPATH="/config/services/abcde"
ABCDE_CONF="/etc/abcde.conf"
VA_PREFIX="Various"

# grab the currently configured config
enable=$(omv_config_get "${OMV_CONFIG_XPATH}/enable")
directory=$(omv_get_sharedfolder_path $(omv_config_get "${OMV_CONFIG_XPATH}/directory"))
owner=$(omv_config_get "${OMV_CONFIG_XPATH}/owner")
format=$(omv_config_get "${OMV_CONFIG_XPATH}/format")
quality=$(omv_config_get "${OMV_CONFIG_XPATH}/quality")
name_format=$(omv_config_get "${OMV_CONFIG_XPATH}/name_format")
generate_playlist=$(omv_config_get "${OMV_CONFIG_XPATH}/generate_playlist")
encoder_count=$(omv_config_get "${OMV_CONFIG_XPATH}/encoder_count")
extra_options=$(omv_config_get "${OMV_CONFIG_XPATH}/extra_options")

# compute additional arguments
playlist_format="${name_format%/*}"'/${ALBUMFILE}.m3u'

actions="cddb,read,encode,tag,move,clean"
if [ "${generate_playlist}" == "1" ]; then
    actions="cddb,playlist,read,encode,tag,move,clean"
fi

# generate abcde.conf
cat <<EOF > ${ABCDE_CONF}
# ------------------/etc/abcde.conf----------------- #
#          OMV generated abcde config file
#       http://andrews-corner.org/abcde.html
# -------------------------------------------------- #

# Encode tracks immediately after reading. Saves disk space, gives
# better reading of 'scratchy' disks and better troubleshooting of
# encoding process but slows the operation of abcde quite a bit:
LOWDISK=y

# Specify the method to use to retrieve the track information,
# the alternative is to specify 'cddb':
CDDBMETHOD=musicbrainz

# Specify the encoders to use.
FLACENCODERSYNTAX=flac
MP3ENCODERSYNTAX=lame 

# Specify the path to the selected encoder. In most cases the encoder
# should be in your $PATH as I illustrate below, otherwise you will 
# need to specify the full path. For example: /usr/bin/flac
FLAC=flac
LAME=lame

# Specify your required encoding options here. Multiple options can
# be selected as '--best --another-option' etc.
# Overall bitrate is about 880 kbs/s with level 8.
FLACOPTS='-s -e -V -${quality}' 
# The '-V 2' option gives VBR encoding between 170-210 kbits/s.
LAMEOPTS='-V ${quality}'

# Output type for selected format.
OUTPUTTYPE="${format}"

# The cd ripping program to use. There are a few choices here: cdda2wav,
# dagrab, cddafs (Mac OS X only) and flac. New to abcde 2.7 is 'libcdio'.
CDROMREADERSYNTAX=cdparanoia            
                                     
# Give the location of the ripping program and pass any extra options,
# if using libcdio set 'CD_PARANOIA=cd-paranoia'.
CDPARANOIA=cdparanoia  
CDPARANOIAOPTS="--never-skip=40"

# Give the location of the CD identification program:       
CDDISCID=cd-discid            
                               
# Give the base location here for the encoded music files.
OUTPUTDIR="${directory}"               

# The default actions that abcde will take.
ACTIONS=${actions}
              
# Decide here how you want the tracks labelled for a standard 'single-artist',
# multi-track encode and also for a multi-track, 'various-artist' encode:
OUTPUTFORMAT='${name_format}'
VAOUTPUTFORMAT='${VA_PREFIX}-${name_format}'

# Create playlists for single and various-artist encodes.
PLAYLISTFORMAT='${playlist_format}'
VAPLAYLISTFORMAT='${VA_PREFIX}-${playlist_format}'

# This function takes out dots preceding the album name, and removes a grab
# bag of illegal characters. It allows spaces, if you do not wish spaces add
# in -e 's/ /_/g' after the first sed command.
mungefilename ()
{
  cur_date=$(ps -o lstart= -p $PPID)
  echo "$@" | sed "s^Unknown Artist^Unknown Artist - $cur_date^g" | sed -e 's/^\.*//' | tr -d ":><|*/\"'?[:cntrl:]"
}

# What extra options?
MAXPROCS=${encoder_count}               # Run a few encoders simultaneously
PADTRACKS=y                             # Makes tracks 01 02 not 1 2
EXTRAVERBOSE=2                          # Useful for debugging
COMMENT='abcde version 2.7.1'           # Place a comment...
EJECTCD=y  
EOF

# done
exit 0