#!/bin/sh
set -e
. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions
case "$1" in
    configure)
        SERVICE_XPATH_NAME="abcde"
        SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"
        # Add the default configuration
        if ! omv_config_exists "${SERVICE_XPATH}"; then
            omv_config_add_element "/config/services" "${SERVICE_XPATH_NAME}"
            omv_config_add_element "${SERVICE_XPATH}" "enable" "0"
            omv_config_add_element "${SERVICE_XPATH}" "directory" ""
            omv_config_add_element "${SERVICE_XPATH}" "owner" ""
            omv_config_add_element "${SERVICE_XPATH}" "format" "mp3"
            omv_config_add_element "${SERVICE_XPATH}" "quality" "5"
            omv_config_add_element "${SERVICE_XPATH}" "name_format" ""
            omv_config_add_element "${SERVICE_XPATH}" "generate_playlist" "0"
            omv_config_add_element "${SERVICE_XPATH}" "encoder_count" "2"
        fi
        # Activate package triggers. These triggers are only set during the
        # package installation.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;
    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac
#DEBHELPER#
exit 0